# Generated by Django 4.1.3 on 2022-11-16 11:47

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Категория"
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Название"
                    ),
                ),
                ("slug", models.SlugField(max_length=200)),
                ("image", models.FileField(blank=True, upload_to="")),
                (
                    "sizes",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("XXS", "XXS"),
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("stock", models.PositiveIntegerField()),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товары",
                "verbose_name_plural": "Товары",
                "ordering": ("name",),
                "index_together": {("id", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.FileField(upload_to=shop.models.get_upload_path)),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
