# Generated by Django 4.1.3 on 2022-11-16 13:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="Изображения"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("XXS", "XXS"),
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=17,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(verbose_name="Остаток"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="images",
            field=models.FileField(
                upload_to=shop.models.get_upload_path, verbose_name="Изображения"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.product",
                verbose_name="Товар",
            ),
        ),
    ]
