# Generated by Django 4.1.3 on 2022-11-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_image_alter_product_sizes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Images",
                to="shop.productimage",
                verbose_name="Изображения",
            ),
        ),
    ]
