# Generated by Django 4.1.3 on 2022-11-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True,
                upload_to="<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>",
                verbose_name="Изображения",
            ),
        ),
    ]
